# Part 1. Data Understanding - Banking Marketing Dataset

### The dataset in this project was created by S. Moro, P. Rita, and P. Cortez and was obtained from UCI Machine Learning Repository. It contains information about direct marketing campaigns conducted by a Portuguese banking institution, where the authors' goal was to predict whether a client would subscribe to a term deposit (target variable y).

In [1]:
import pandas as pd

### Initial preview of the dataset.

Viewing the first rows of the dataset helps confirm that the data was loaded correctly and provides an initial understanding of the variables.

In [11]:
df = pd.read_csv('bank.csv', sep=";")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

### Dataset dimensions
The size of the dataset indicates how many observations (rows) and variables (columns) are available for analysis.

In [14]:
df.shape

(4521, 17)

### Data types and potential missing values

Examining data types ensures variables are in appropriate formats for analysis. Checking for missing values helps identify potential data quality issues that may require preprocessing.

In [10]:
summary = pd.DataFrame({
    "data_type":df.dtypes,
    "unique_values":df.nunique(),
    "missing_values":df.isna().sum()
})
summary

          data_type  unique_values  missing_values
age           int64             67               0
job             str             12               0
marital         str              3               0
education       str              4               0
default         str              2               0
balance       int64           2353               0
housing         str              2               0
loan            str              2               0
contact         str              3               0
day           int64             31               0
month           str             12               0
duration      int64            875               0
campaign      int64             32               0
pdays         int64            292               0
previous      int64             24               0
poutcome        str              4               0
y               str              2               0

### Variables included in the dataset
Reviewing the list of variables helps identify the types of information available, including demographic characteristics, financial indicators, and details of a previous marketing campaign.

In [15]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='str')


### Consistency with the metadata

The authors of the dataset has provided the metadata describing each variable, its role, it's type, and demographic. Reviewing the unique values of categorical variables helps confirm consistency between the dataset and provided metadata, and helps identify placeholders values such as "unknown".

#### Categorical Values Overview

In [28]:
categorical_variables = df.select_dtypes(exclude=["int", "float"])

for column in categorical_variables.columns:
    print(f"\n{column}")
    print(df[column].unique())

job
<StringArray>
[   'unemployed',      'services',    'management',   'blue-collar',
 'self-employed',    'technician',  'entrepreneur',        'admin.',
       'student',     'housemaid',       'retired',       'unknown']
Length: 12, dtype: str

marital
<StringArray>
['married', 'single', 'divorced']
Length: 3, dtype: str

education
<StringArray>
['primary', 'secondary', 'tertiary', 'unknown']
Length: 4, dtype: str

default
<StringArray>
['no', 'yes']
Length: 2, dtype: str

housing
<StringArray>
['no', 'yes']
Length: 2, dtype: str

loan
<StringArray>
['no', 'yes']
Length: 2, dtype: str

contact
<StringArray>
['cellular', 'unknown', 'telephone']
Length: 3, dtype: str

month
<StringArray>
['oct', 'may', 'apr', 'jun', 'feb', 'aug', 'jan', 'jul', 'nov', 'sep', 'mar',
 'dec']
Length: 12, dtype: str

poutcome
<StringArray>
['unknown', 'failure', 'other', 'success']
Length: 4, dtype: str

y
<StringArray>
['no', 'yes']
Length: 2, dtype: str

Previously, when checking for missing values, the results showed that there is no missing data. However, several categorical variables contain the value 'unknown', which may represent missing or unavailable information and will be addressed during preprocessing.

#### Numerical Values Overview

Numerical variables represent continuous or count-based values. Descriptive statistics provide information about distribution, central tendency and variability.

In [27]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

### Distribution of the target variable

The target variable y indicates whether a client subscribed to a term deposit. Examining this distribution helps determine if there is a balance between the two outcomes - yes or no.

In [12]:
df["y"].value_counts()

y
no     4000
yes     521
Name: count, dtype: int64

In [13]:
df["y"].value_counts(normalize=True)

y
no     0.88476
yes    0.11524
Name: proportion, dtype: float64